[config]
ignore_pr_target_branches = ["master"]
ignore_pr_title = ["^merge"]
reasoning_effort = 'high'

[pr_description] # /describe #
publish_description_as_comment = true
publish_labels = true
enable_pr_type = false
add_original_user_description = false

[rag_arguments]
enable_rag=true

[pr_reviewer] # /review #
require_score_review = true
require_ticket_analysis_review = true
num_max_findings = 2
publish_output_no_suggestions = false

[pr_compliance]
enable_ticket_labels = true
enable_custom_compliance_section = false
enable_user_defined_compliance_labels = false
enable_security_section = false
enable_codebase_duplication_section = false

[pr_code_suggestions]
num_code_suggestions = 1
commitable_code_suggestions = true
wiki_page_accepted_suggestions = false
enable_chat_in_code_suggestions = false

[pr_custom_prompt] # /custom_prompt #
num_code_suggestions_per_chunk = 1

[pr_add_docs]

[github_app]
pr_commands = [
    "/describe",
    "/review"
]

# settings for "pull_request" event with "synchronize" action - used to detect and handle push triggers for new commits
handle_push_trigger = true
push_commands = [
    "/describe"
]

[jira]
jira_base_url = "https://statscore.atlassian.net"

# all available configuration options
# https://github.com/qodo-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml/

# documentation of options
# https://qodo-merge-docs.qodo.ai/tools/
